### ISSUE TITLE
decode messages from prometheus remote write

### ISSUE THREAD

**Issue by hkousha** [claws/prometheus_metrics_proto#4]
Was planning on using this for decoding Prometheus remote_write messages but can't decode the messages.

```
Error parsing message
```

**Comment by claws** [comment]
I don't think this library will help you with that. I'm pretty sure that Prometheus will be using some kind of remote write adapter that will apply some additional framing - if not completely changing the data format.

This library implements the binary format that Prometheus used a while back, pre version 2.0. I'm pretty sure they have since moved to solely supporting the text format. See [here](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md).

**Comment by hkousha** [comment]
Looking at the docs looks like [this](https://github.com/prometheus/prometheus/blob/master/prompb/remote.proto) is the proto it uses. compiling that to python.

**Comment by zequequiel** [comment]
@hkousha did you get Prometheus remote_write messages decoded after compiling the [WriteRequest](https://github.com/prometheus/prometheus/blob/master/prompb/remote.proto) message?
